image: docker.io/hugomods/hugo:go-git
variables:
  GIT_SUBMODULE_STRATEGY: recursive
test:
  script:
    - apk add --update --no-cache go
    - hugo
  except:
    - master
pages:
  script:
    - apk add --update --no-cache go
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
